spring:
  application:
    name: search-backend
  # MySQL 配置
  # todo：修改MySQL配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://128.0.0.129:3306/springboot_init
    username: root
    password: root
  # Redis 配置
  # todo：修改Redis配置
  redis:
    host: 128.0.0.129
    port: 6379
    timeout: 5000
  # 文档 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8888
  servlet:
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）